11 
    de.renew.gui.CPNDrawing 318 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1840 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1874 592 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1844 "FillColor" "Color" 0 255 0 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 291 153 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1845 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1871 675 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1846 "FontStyle" "Int" 1 2 1883 675 1884 612 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1847 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1958 609 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1848 "FontStyle" "Int" 1 3 1963 627 1935 667 1895 679 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 3   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1870 "FillColor" "Color" 0 255 0 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 288 73 20 21 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1871 "FontStyle" "Int" 1 3 303 92 321 124 306 153 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 13  
            CH.ifa.draw.standard.ChopBoxConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1872 "FontStyle" "Int" 1 3 299 153 287 127 296 93 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 13   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1873 "FontStyle" "Int" 1 3 1889 675 1923 630 1959 621 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1891 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1925 663 "x" "SansSerif" 1 16 0 REF 9 
            CH.ifa.draw.standard.OffsetLocator 1 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1909 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 318 74 "raw material" "SansSerif" 1 16 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 75 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1943 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 2021 670 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1944 "FontStyle" "Int" 1 2 1895 682 2022 680 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 3  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1945 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1924 673 "holonId" "SansSerif" 1 16 0 REF 33 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1913 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 182 152 "guard x > 0" "SansSerif" 1 16 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -70 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1955 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 316 167 "ph: new productHolon(holonId)" "SansSerif" 1 16 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 150 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1956 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 293 221 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1958 "FontStyle" "Int" 1 2 303 169 303 222 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 2  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1970 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1542 512 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1971 "FontStyle" "Int" 1 2 1884 593 1884 526 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1978 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1872 510 24 16 NULL    
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1975 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1373 507 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1976 "FontStyle" "Int" 1 2 1542 519 1393 517 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 51  
            CH.ifa.draw.figures.ChopEllipseConnector REF 57   REF 56 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1980 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1704 510 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1981 "FontStyle" "Int" 1 2 1872 518 1724 520 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector REF 62   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1988 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1407 507 "[holonId, rht]" "SansSerif" 1 16 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator -1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1989 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 293 74 "1" "SansSerif" 1 16 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1991 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 496 224 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 1992 "FontStyle" "Int" 1 2 313 231 496 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 73   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1993 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 391 221 "ph" "SansSerif" 1 16 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 1998 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 292 340 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2002 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 601 339 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2004 "FontStyle" "Int" 1 2 602 349 316 348 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 82  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2008 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 885 343 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2009 "FontStyle" "Int" 1 2 885 350 621 349 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 87  
            CH.ifa.draw.figures.ChopEllipseConnector REF 82   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2012 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 887 221 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2014 "FontStyle" "Int" 1 2 520 231 888 231 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 73  
            CH.ifa.draw.figures.ChopEllipseConnector REF 92   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2015 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 649 224 "[ph, service]" "SansSerif" 1 16 0 REF 93 
            CH.ifa.draw.standard.OffsetLocator 1 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2016 "FontStyle" "Int" 1 2 897 241 897 343 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 92  
            CH.ifa.draw.standard.ChopBoxConnector REF 87   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2017 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 840 284 "[ph, service]" "SansSerif" 1 16 0 REF 100 
            CH.ifa.draw.standard.OffsetLocator -1 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2019 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1154 341 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2021 "FontStyle" "Int" 1 2 1155 351 909 351 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 107  
            CH.ifa.draw.standard.ChopBoxConnector REF 87   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2022 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 948 341 "[provider, service]" "SansSerif" 1 16 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator -2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2024 "FontStyle" "Int" 1 2 303 340 303 241 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 81  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2028 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1107 322 "service catalog" "SansSerif" 1 16 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator 10 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2064 "FontStyle" "Int" 1 2 1883 510 1882 458 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 56  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2418 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1872 438 20 20 NULL 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2030 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1728 348 20 20 NULL     REF 127 
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2033 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1480 347 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2066 "FontStyle" "Int" 1 2 1729 358 1504 355 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 127  
            CH.ifa.draw.standard.ChopBoxConnector REF 128   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2067 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1530 346 "[holonId, services]" "SansSerif" 1 16 0 REF 129 
            CH.ifa.draw.standard.OffsetLocator -4 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2038 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1395 342 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2039 "FontStyle" "Int" 1 2 1480 354 1415 352 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 128  
            CH.ifa.draw.figures.ChopEllipseConnector REF 136   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2041 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1438 344 "sr" "SansSerif" 1 16 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2043 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1284 344 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2045 "FontStyle" "Int" 1 2 1284 351 1174 351 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 107   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2048 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1210 342 "item" "SansSerif" 1 16 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2069 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 152 524 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2070 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 150 226 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2072 "FontStyle" "Int" 1 2 294 231 174 233 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 46  
            CH.ifa.draw.standard.ChopBoxConnector REF 153   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2074 "FontStyle" "Int" 1 2 162 242 162 525 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 153  
            CH.ifa.draw.figures.ChopEllipseConnector REF 152   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2100 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 401 525 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2109 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 622 518 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2110 "FontStyle" "Int" 1 2 425 532 623 528 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 162  
            CH.ifa.draw.figures.ChopEllipseConnector REF 163   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2118 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 828 521 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2119 "FontStyle" "Int" 1 2 642 528 828 528 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 163  
            CH.ifa.draw.standard.ChopBoxConnector REF 168   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2122 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1042 513 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2125 "FontStyle" "Int" 1 2 852 528 1043 523 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 168  
            CH.ifa.draw.figures.ChopEllipseConnector REF 173   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2126 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 871 516 "[holonId, ph, rht]" "SansSerif" 1 16 0 REF 174 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2128 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1260 512 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2129 "FontStyle" "Int" 1 2 1062 523 1260 520 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 173  
            CH.ifa.draw.standard.ChopBoxConnector REF 181   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2131 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1085 512 "[holonId, ph, rht]" "SansSerif" 1 16 0 REF 182 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2141 "FontStyle" "Int" 1 2 1272 512 1272 459 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 181  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2416 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1262 439 20 20 NULL REF 127    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2144 "FontStyle" "Int" 1 2 1282 528 1398 621 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 181  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2483 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1395 616 20 20 NULL    
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2149 "FillColor" "Color" 112 219 147 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1262 859 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2155 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1917 1099 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2156 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1913 1177 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2157 "FontStyle" "Int" 1 2 1925 1177 1927 1119 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 201  
            CH.ifa.draw.figures.ChopEllipseConnector REF 200   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2158 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 2004 1104 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2159 "FontStyle" "Int" 1 3 2006 1118 1990 1126 1933 1177 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 206  
            CH.ifa.draw.standard.ChopBoxConnector REF 201   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2160 "FontStyle" "Int" 1 3 1937 1179 1992 1157 2010 1123 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 201  
            CH.ifa.draw.figures.ChopEllipseConnector REF 206   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2166 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 2077 1172 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2167 "FontStyle" "Int" 1 2 1937 1184 2078 1182 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 201  
            CH.ifa.draw.figures.ChopEllipseConnector REF 215   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2168 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1973 1175 "holonId" "SansSerif" 1 16 0 REF 216 
            CH.ifa.draw.standard.OffsetLocator -2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2171 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1588 1022 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2172 "FontStyle" "Int" 1 2 1927 1100 1927 1036 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 200  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2176 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1916 1020 24 16 NULL    
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2174 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1411 1019 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2175 "FontStyle" "Int" 1 2 1588 1029 1431 1029 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 223  
            CH.ifa.draw.figures.ChopEllipseConnector REF 229   REF 228 
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2177 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1754 1019 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2178 "FontStyle" "Int" 1 2 1916 1028 1774 1029 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector REF 234   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2179 "FontStyle" "Int" 1 2 1755 1029 1612 1029 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 234  
            CH.ifa.draw.standard.ChopBoxConnector REF 223   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2182 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1445 1018 "[holonId, rhm]" "SansSerif" 1 16 0 REF 230 
            CH.ifa.draw.standard.OffsetLocator -1 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2190 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1913 1059 "rhm" "SansSerif" 1 16 0 REF 224 
            CH.ifa.draw.standard.OffsetLocator 3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2181 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1619 1020 "[holonId, rhm]" "SansSerif" 1 16 0 REF 239 
            CH.ifa.draw.standard.OffsetLocator -1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2180 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1781 1018 "[holonId, rhm]" "SansSerif" 1 16 0 REF 235 
            CH.ifa.draw.standard.OffsetLocator -1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2297 "FontStyle" "Int" 1 2 1282 869 1406 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 199  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2518 "FillColor" "Color" 112 219 147 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1406 861 24 16 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2298 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1333 860 "ph" "SansSerif" 1 16 0 REF 255 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2121 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 656 519 "[holonId, ph, rht]" "SansSerif" 1 16 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2111 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 450 518 "[holonId, ph, rht]" "SansSerif" 1 16 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 2 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2124 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1013 485 "in transit" "SansSerif" 1 16 0 REF 173 
            CH.ifa.draw.standard.OffsetLocator 1 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2114 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 576 492 "loading cargo" "SansSerif" 1 16 0 REF 163 
            CH.ifa.draw.standard.OffsetLocator 3 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1986 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1743 509 "[holonId, rht]" "SansSerif" 1 16 0 REF 63 
            CH.ifa.draw.standard.OffsetLocator 4 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2304 "FillColor" "Color" 112 219 147 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 98 862 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2308 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 98 1025 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2311 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 358 1029 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2315 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 600 1029 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2316 "FontStyle" "Int" 1 2 382 1037 601 1039 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 280  
            CH.ifa.draw.figures.ChopEllipseConnector REF 281   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2319 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 805 1030 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2320 "FontStyle" "Int" 1 2 620 1039 805 1038 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 281  
            CH.ifa.draw.standard.ChopBoxConnector REF 286   
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2321 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1020 1024 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2322 "FontStyle" "Int" 1 2 829 1037 1021 1034 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 286  
            CH.ifa.draw.figures.ChopEllipseConnector REF 291   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2323 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 845 1026 "[holonId, ph, rhm]" "SansSerif" 1 16 0 REF 292 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2324 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1238 1023 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2325 "FontStyle" "Int" 1 2 1040 1034 1238 1031 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 291  
            CH.ifa.draw.standard.ChopBoxConnector REF 299   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2326 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1059 1023 "[holonId, ph, rhm]" "SansSerif" 1 16 0 REF 300 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2330 "FontStyle" "Int" 1 2 1250 1039 1253 1134 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 299  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2332 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1243 1133 20 20 NULL    REF 311 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2337 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 629 1029 "[holonId, ph, rhm]" "SansSerif" 1 16 0 REF 287 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2338 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 413 1026 "[holonId, ph, rhm]" "SansSerif" 1 16 0 REF 282 
            CH.ifa.draw.standard.OffsetLocator 2 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2339 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 973 996 "in production" "SansSerif" 1 16 0 REF 291 
            CH.ifa.draw.standard.OffsetLocator 1 -29 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2340 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 544 1003 "loading product" "SansSerif" 1 16 0 REF 281 
            CH.ifa.draw.standard.OffsetLocator 3 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2351 "FontStyle" "Int" 1 2 109 878 108 1026 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 278  
            CH.ifa.draw.figures.ChopEllipseConnector REF 279   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2353 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 52 943 "[holonId, ph]" "SansSerif" 1 16 0 REF 324 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2354 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1237 1192 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2355 "FontStyle" "Int" 1 2 1253 1153 1249 1192 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 311  
            CH.ifa.draw.standard.ChopBoxConnector REF 331   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2356 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1240 1163 "ph" "SansSerif" 1 16 0 REF 332 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2361 "FontStyle" "Int" 1 2 1249 1023 1249 970 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 299  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2408 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1239 950 20 20 NULL REF 127    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2365 "FontStyle" "Int" 1 2 1237 1199 1140 1199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 331  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2422 "FillColor" "Color" 153 255 255 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1120 1189 20 20 NULL REF 46    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2366 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1177 1190 "ph" "SansSerif" 1 16 0 REF 344 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2001 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 205 361 "ph:foundProvider(provider)" "SansSerif" 1 16 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 22 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2025 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 288 285 "ph" "SansSerif" 1 16 0 REF 115 
            CH.ifa.draw.standard.OffsetLocator -4 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1959 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 292 183 "ph" "SansSerif" 1 16 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2073 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 237 219 "ph" "SansSerif" 1 16 0 REF 154 
            CH.ifa.draw.standard.OffsetLocator 14 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2369 "FontStyle" "Int" 1 2 1927 1020 1926 966 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 228  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2420 "FillColor" "Color" 255 204 102 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1916 946 20 20 NULL REF 127    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2370 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1844 984 "[holonId, services]" "SansSerif" 1 16 0 REF 364 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2385 "FontStyle" "Int" 1 2 369 979 369 1029 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2410 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 359 959 20 20 NULL REF 229   
            CH.ifa.draw.standard.ChopBoxConnector REF 280   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2387 "FontStyle" "Int" 1 2 412 468 412 525 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2412 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 402 448 20 20 NULL REF 57   
            CH.ifa.draw.standard.ChopBoxConnector REF 162   REF 343 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2409 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1126 923 "ready To Register Service" "SansSerif" 1 16 0 REF 343 
            CH.ifa.draw.standard.OffsetLocator -8 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 375 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2411 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 313 925 "machines \nwaiting for job" "SansSerif" 1 16 0 REF 375 
            CH.ifa.draw.standard.OffsetLocator 7 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2386 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 307 989 "[holonId, rhm]" "SansSerif" 1 16 0 REF 372 
            CH.ifa.draw.standard.OffsetLocator 1 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 380 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2413 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 424 433 "transportes \nwaiting for job" "SansSerif" 1 16 0 REF 380 
            CH.ifa.draw.standard.OffsetLocator 75 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2388 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 358 484 "[holonId, rht]" "SansSerif" 1 16 0 REF 377 
            CH.ifa.draw.standard.OffsetLocator 5 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2414 "FontStyle" "Int" 1 2 1308 352 1396 352 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 144  
            CH.ifa.draw.figures.ChopEllipseConnector REF 136   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2415 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1343 343 "sr" "SansSerif" 1 16 0 REF 397 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 193 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2417 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1172 413 "ready To Register Service" "SansSerif" 1 16 0 REF 193 
            CH.ifa.draw.standard.OffsetLocator 15 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 126 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2419 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1779 417 "ready To Register Service" "SansSerif" 1 16 0 REF 126 
            CH.ifa.draw.standard.OffsetLocator 12 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 368 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2421 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1840 930 "ready To Register Service" "SansSerif" 1 16 0 REF 368 
            CH.ifa.draw.standard.OffsetLocator 29 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 348 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2423 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1048 1167 "select next Service" "SansSerif" 1 16 0 REF 348 
            CH.ifa.draw.standard.OffsetLocator 3 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2065 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1812 466 "[holonId, services]" "SansSerif" 1 16 0 REF 122 
            CH.ifa.draw.standard.OffsetLocator 12 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2427 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 96 1131 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2428 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 357 1127 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2430 "FontStyle" "Int" 1 2 120 1138 358 1137 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 420  
            CH.ifa.draw.figures.ChopEllipseConnector REF 421   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2432 "FontStyle" "Int" 1 2 367 1128 369 1045 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 421  
            CH.ifa.draw.standard.ChopBoxConnector REF 280   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2434 "FontStyle" "Int" 1 2 108 1045 108 1131 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 279  
            CH.ifa.draw.standard.ChopBoxConnector REF 420   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2435 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 52 1079 "[holonId, ph]" "SansSerif" 1 16 0 REF 430 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2438 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 149 608 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2439 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 402 601 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2440 "FontStyle" "Int" 1 2 173 615 403 611 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 437  
            CH.ifa.draw.figures.ChopEllipseConnector REF 438   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2442 "FontStyle" "Int" 1 2 412 602 412 541 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 438  
            CH.ifa.draw.standard.ChopBoxConnector REF 162   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2444 "FontStyle" "Int" 1 2 162 544 161 608 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 152  
            CH.ifa.draw.standard.ChopBoxConnector REF 437   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2445 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 105 567 "[holonId, ph]" "SansSerif" 1 16 0 REF 447 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2459 "FontStyle" "Int" 1 2 1705 520 1566 520 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 62  
            CH.ifa.draw.standard.ChopBoxConnector REF 51   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2460 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1576 511 "[holonId, rht]" "SansSerif" 1 16 0 REF 454 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2477 "FontStyle" "Int" 1 2 1272 528 1272 860 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 181  
            CH.ifa.draw.figures.ChopEllipseConnector REF 199   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2482 "FillColor" "Color" 255 102 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1584 614 24 16 NULL  REF 198 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2484 "FontStyle" "Int" 1 2 1415 626 1584 622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 198  
            CH.ifa.draw.standard.ChopBoxConnector REF 465   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2485 "FontStyle" "Int" 1 2 1605 614 1707 527 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 465  
            CH.ifa.draw.figures.ChopEllipseConnector REF 62   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2486 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1440 615 "[holonId, rht]" "SansSerif" 1 16 0 REF 466 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2487 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1597 561 "[holonId, rht]" "SansSerif" 1 16 0 REF 470 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2488 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1511 641 "rht:getReadyForNext()" "SansSerif" 1 16 0 REF 465 
            CH.ifa.draw.standard.OffsetLocator 16 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2504 "FontStyle" "Int" 1 2 1262 1038 1428 1146 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 299  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2508 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1425 1140 20 20 NULL    
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2507 "FillColor" "Color" 0 153 204 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1604 1144 24 16 NULL  REF 487 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2509 "FontStyle" "Int" 1 2 1445 1150 1604 1151 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 487  
            CH.ifa.draw.standard.ChopBoxConnector REF 488   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2510 "FontStyle" "Int" 1 2 1625 1144 1757 1035 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 488  
            CH.ifa.draw.figures.ChopEllipseConnector REF 234   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2512 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1461 1141 "[holonId, rhm]" "SansSerif" 1 16 0 REF 489 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2513 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1628 1080 "[holonId, rhm]" "SansSerif" 1 16 0 REF 493 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2514 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1527 1171 "rhm:getReadyForNext()" "SansSerif" 1 16 0 REF 488 
            CH.ifa.draw.standard.OffsetLocator 16 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2515 "FillColor" "Color" 112 219 147 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1511 859 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2517 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1524 855 "warehouse" "SansSerif" 1 16 0 REF 506 
            CH.ifa.draw.standard.OffsetLocator 52 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 259 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2481 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1358 836 "ph:arrivewh()" "SansSerif" 1 16 0 REF 259 
            CH.ifa.draw.standard.OffsetLocator -1 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2519 "FontStyle" "Int" 1 2 1430 869 1512 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 259  
            CH.ifa.draw.figures.ChopEllipseConnector REF 506   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2520 "FontStyle" "Int" 1 2 1263 869 122 869 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 199  
            CH.ifa.draw.standard.ChopBoxConnector REF 278   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2521 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 117 881 "ph:arrive()" "SansSerif" 1 16 0 REF 278 
            CH.ifa.draw.standard.OffsetLocator 53 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2522 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 850 860 "ph" "SansSerif" 1 16 0 REF 517 
            CH.ifa.draw.standard.OffsetLocator 169 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2523 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1460 860 "ph" "SansSerif" 1 16 0 REF 513 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2524 "FillColor" "Color" 255 204 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1189 195 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2525 "FillColor" "Color" 153 255 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1187 255 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2526 "FillColor" "Color" 153 255 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1318 254 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2527 "FillColor" "Color" 153 255 153 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 1423 254 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2528 "FontStyle" "Int" 1 2 1199 215 1199 255 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 530  
            CH.ifa.draw.standard.ChopBoxConnector REF 531   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2529 "FontStyle" "Int" 1 2 1211 263 1319 264 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 531  
            CH.ifa.draw.figures.ChopEllipseConnector REF 532   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2530 "FontStyle" "Int" 1 2 1338 264 1423 262 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 532  
            CH.ifa.draw.standard.ChopBoxConnector REF 533   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2532 "TextAlignment" "Int" 1 "FillColor" "Color" 153 255 153 255 1192 196 "[]" "SansSerif" 1 16 0 REF 530 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2533 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1237 254 "logger" "SansSerif" 1 16 0 REF 538 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2534 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1352 254 "logger" "SansSerif" 1 16 0 REF 542 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "FontSize" "Int" 16 "FigureWithID" "Int" 2535 "FontStyle" "Int" 1 "FillColor" "Color" 153 255 153 255 1366 177 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2536 "FontStyle" "Int" 1 2 1372 193 1333 257 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 556  
            CH.ifa.draw.figures.ChopEllipseConnector REF 532   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2112 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 428 542 "rht:start(service)" "SansSerif" 1 16 0 REF 162 
            CH.ifa.draw.standard.OffsetLocator 92 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2555 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1334 1002 "this:logInfo(\"provider_ready:\" + holonId + \":\" +rhm );" "SansSerif" 1 16 0 REF 223 
            CH.ifa.draw.standard.OffsetLocator -31 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2559 "FillColor" "Color" 0 255 0 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 658 80 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2560 "FillColor" "Color" 0 255 0 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 707 43 20 21 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2561 "FontStyle" "Int" 1 3 713 62 703 81 682 85 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 569  
            CH.ifa.draw.standard.ChopBoxConnector REF 568   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2562 "FontStyle" "Int" 1 3 672 80 681 58 708 54 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 568  
            CH.ifa.draw.figures.ChopEllipseConnector REF 569   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2566 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 549 79 "guard x > 0" "SansSerif" 1 16 0 REF 568 
            CH.ifa.draw.standard.OffsetLocator -70 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2572 "FontStyle" "Int" 1 2 658 92 312 228 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 568  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.TransitionFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2574 "FillColor" "Color" 0 255 0 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 131 34 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 5 "FontStyle" "Int" 1 "FigureWithID" "Int" 2575 "FillColor" "Color" 0 255 0 255 "FontSize" "Int" 16 "FrameColor" "Color" 0 0 0 255 95 97 20 21 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2576 "FontStyle" "Int" 1 3 114 103 143 84 143 50 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 586  
            CH.ifa.draw.standard.ChopBoxConnector REF 585   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2577 "FontStyle" "Int" 1 3 134 50 113 71 107 98 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 585  
            CH.ifa.draw.figures.ChopEllipseConnector REF 586   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2581 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 22 33 "guard x > 0" "SansSerif" 1 16 0 REF 585 
            CH.ifa.draw.standard.OffsetLocator -70 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2584 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 100 98 "0" "SansSerif" 1 16 0 REF 586 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "FontSize" "Int" 16 "FigureWithID" "Int" 2585 "FontStyle" "Int" 1 2 149 50 298 224 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 585  
            CH.ifa.draw.figures.ChopEllipseConnector REF 46   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2583 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 170 36 "ph: new productHolon(holonId)" "SansSerif" 1 16 0 REF 585 
            CH.ifa.draw.standard.OffsetLocator 164 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1954 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 323 147 "action holonId = pt.nfriacowboy.presib.hermes.utils.PresibUtils.Companion.holonIdBuilder(\"ph\", 1)" "SansSerif" 1 16 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 455 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2582 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 169 8 "action holonId = pt.nfriacowboy.presib.hermes.utils.PresibUtils.Companion.holonIdBuilder(\"ph\", 3)" "SansSerif" 1 16 0 REF 585 
            CH.ifa.draw.standard.OffsetLocator 461 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2563 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 731 42 "raw material" "SansSerif" 1 16 0 REF 569 
            CH.ifa.draw.standard.OffsetLocator 69 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2565 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 705 64 "x" "SansSerif" 1 16 0 REF 570 
            CH.ifa.draw.standard.OffsetLocator 13 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1912 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 327 108 "x" "SansSerif" 1 16 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 20 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1911 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 254 111 "x-1" "SansSerif" 1 16 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator -25 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2580 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 140 66 "x" "SansSerif" 1 16 0 REF 587 
            CH.ifa.draw.standard.OffsetLocator 17 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2578 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 33 118 "raw material" "SansSerif" 1 16 0 REF 586 
            CH.ifa.draw.standard.OffsetLocator -17 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2579 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 86 62 "x-1" "SansSerif" 1 16 0 REF 591 
            CH.ifa.draw.standard.OffsetLocator -20 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2587 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 199 102 "ph" "SansSerif" 1 16 0 REF 601 
            CH.ifa.draw.standard.OffsetLocator -13 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2569 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 707 45 "0" "SansSerif" 1 16 0 REF 569 
            CH.ifa.draw.standard.OffsetLocator -5 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2564 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 655 47 "x-1" "SansSerif" 1 16 0 REF 574 
            CH.ifa.draw.standard.OffsetLocator -21 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2567 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 665 103 "action holonId = pt.nfriacowboy.presib.hermes.utils.PresibUtils.Companion.holonIdBuilder(\"ph\", 2)" "SansSerif" 1 16 0 REF 568 
            CH.ifa.draw.standard.OffsetLocator 430 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2568 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 669 118 "ph: new productHolon(holonId)" "SansSerif" 1 16 0 REF 568 
            CH.ifa.draw.standard.OffsetLocator 136 39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2573 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 575 113 "ph" "SansSerif" 1 16 0 REF 581 
            CH.ifa.draw.standard.OffsetLocator 101 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2104 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 10 201 "ph:transportProvider(holonId)" "SansSerif" 1 16 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator -19 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2071 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 8 179 "ph:loadToTransport()" "SansSerif" 1 16 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator -60 -46 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2538 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1403 158 ":logError(message)" "SansSerif" 1 16 0 REF 556 
            CH.ifa.draw.standard.OffsetLocator 110 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2539 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1404 185 "logger.error(message)" "SansSerif" 1 16 0 REF 556 
            CH.ifa.draw.standard.OffsetLocator 126 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2531 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1188 280 "action logger =  new pt.nfriacowboy.presib.hermes.logger.NetLogger().getLogger(\"Playground\")" "SansSerif" 1 16 0 REF 531 
            CH.ifa.draw.standard.OffsetLocator 419 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2540 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1455 231 ":logInfo(message)" "SansSerif" 1 16 0 REF 533 
            CH.ifa.draw.standard.OffsetLocator 100 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2541 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1457 255 "logger.info(message)" "SansSerif" 1 16 0 REF 533 
            CH.ifa.draw.standard.OffsetLocator 116 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1983 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1663 532 "services Published" "SansSerif" 1 16 0 REF 62 
            CH.ifa.draw.standard.OffsetLocator 31 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2556 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1318 476 "this:logInfo(\"provider_ready:\" + holonId + \":\" +rht );" "SansSerif" 1 16 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator -5 -35 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2426 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1542 529 "rht:ready()" "SansSerif" 1 16 0 REF 51 
            CH.ifa.draw.standard.OffsetLocator 36 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2193 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1727 1043 "services Published" "SansSerif" 1 16 0 REF 234 
            CH.ifa.draw.standard.OffsetLocator 45 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1977 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1349 438 "transportes \nwaiting for job" "SansSerif" 1 16 0 REF 57 
            CH.ifa.draw.standard.OffsetLocator 29 -60 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2195 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1364 960 "machines \nwaiting for job" "SansSerif" 1 16 0 REF 229 
            CH.ifa.draw.standard.OffsetLocator 6 -50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2362 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1138 987 "[holonId, services]" "SansSerif" 1 16 0 REF 339 
            CH.ifa.draw.standard.OffsetLocator -29 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2173 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1579 1043 "rhm:ready()" "SansSerif" 1 16 0 REF 223 
            CH.ifa.draw.standard.OffsetLocator 31 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2357 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1279 1191 "ph:unloaded()" "SansSerif" 1 16 0 REF 331 
            CH.ifa.draw.standard.OffsetLocator 91 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2331 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1242 1104 "ph" "SansSerif" 1 16 0 REF 307 
            CH.ifa.draw.standard.OffsetLocator 2 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2346 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1147 1043 "ph:currentService(services)" "SansSerif" 1 16 0 REF 299 
            CH.ifa.draw.standard.OffsetLocator 21 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2480 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1262 735 "ph" "SansSerif" 1 16 0 REF 461 
            CH.ifa.draw.standard.OffsetLocator 1 50 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2145 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1352 587 "[holonId, rht]" "SansSerif" 1 16 0 REF 194 
            CH.ifa.draw.standard.OffsetLocator 71 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2117 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 766 546 "ph:startTransport()" "SansSerif" 1 16 0 REF 168 
            CH.ifa.draw.standard.OffsetLocator 13 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2127 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 761 560 "rht:startServiceExecution()" "SansSerif" 1 16 0 REF 168 
            CH.ifa.draw.standard.OffsetLocator 42 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2542 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 674 578 "this:logInfo(\"start_service:\" + holonId + \":\" +ph );" "SansSerif" 1 16 0 REF 168 
            CH.ifa.draw.standard.OffsetLocator 55 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2335 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 789 1056 "ph:load()" "SansSerif" 1 16 0 REF 286 
            CH.ifa.draw.standard.OffsetLocator 11 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2334 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 724 1074 "rhm:startServiceExecution()" "SansSerif" 1 16 0 REF 286 
            CH.ifa.draw.standard.OffsetLocator 32 45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2545 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 644 1092 "this:logInfo(\"start_service:\" + holonId + \":\" +ph );" "SansSerif" 1 16 0 REF 286 
            CH.ifa.draw.standard.OffsetLocator 48 63 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2431 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 135 1128 "[holonId, ph, service]" "SansSerif" 1 16 0 REF 422 
            CH.ifa.draw.standard.OffsetLocator -10 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2433 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 274 1083 "[holonId, ph, service]" "SansSerif" 1 16 0 REF 426 
            CH.ifa.draw.standard.OffsetLocator 0 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2429 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 59 1168 "ph:currentService(service)" "SansSerif" 1 16 0 REF 420 
            CH.ifa.draw.standard.OffsetLocator 70 38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2336 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 373 1061 "rhm:start(service)" "SansSerif" 1 16 0 REF 280 
            CH.ifa.draw.standard.OffsetLocator 84 33 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2446 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 88 626 "ph:currentTransportService(service)" "SansSerif" 1 16 0 REF 437 
            CH.ifa.draw.standard.OffsetLocator 90 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2352 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 52 833 "ph:transformationProvider(holonId)" "SansSerif" 1 16 0 REF 278 
            CH.ifa.draw.standard.OffsetLocator 99 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2349 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 60 502 "Waiting for transport" "SansSerif" 1 16 0 REF 152 
            CH.ifa.draw.standard.OffsetLocator -8 -23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2350 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 39 1002 "Waiting for machine" "SansSerif" 1 16 0 REF 279 
            CH.ifa.draw.standard.OffsetLocator 19 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2142 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1136 472 "[holonId, services]" "SansSerif" 1 16 0 REF 189 
            CH.ifa.draw.standard.OffsetLocator -54 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2441 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 186 605 "[holonId, ph, service]" "SansSerif" 1 16 0 REF 439 
            CH.ifa.draw.standard.OffsetLocator -8 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2443 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 316 574 "[holonId, ph, service]" "SansSerif" 1 16 0 REF 443 
            CH.ifa.draw.standard.OffsetLocator -2 12 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2098 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 106 288 "[holonId, ph]" "SansSerif" 1 16 0 REF 158 
            CH.ifa.draw.standard.OffsetLocator 0 -86 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2013 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 914 219 "requested service" "SansSerif" 1 16 0 REF 92 
            CH.ifa.draw.standard.OffsetLocator 98 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1990 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 312 198 "select next Service" "SansSerif" 1 16 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 94 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2095 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1754 347 "ready To Register Service" "SansSerif" 1 16 0 REF 127 
            CH.ifa.draw.standard.OffsetLocator 131 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2068 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1457 314 "sr: new service_register(holonId, services)" "SansSerif" 1 16 0 REF 128 
            CH.ifa.draw.standard.OffsetLocator 155 -32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2537 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1326 210 "logger" "SansSerif" 1 16 0 REF 557 
            CH.ifa.draw.standard.OffsetLocator 2 -6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2011 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 655 340 "[ph, service, provider]" "SansSerif" 1 16 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2007 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 357 338 "[ph, service, provider]" "SansSerif" 1 16 0 REF 83 
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2052 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1278 373 "sr:publishServices(item)" "SansSerif" 1 16 0 REF 144 
            CH.ifa.draw.standard.OffsetLocator 89 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2547 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 747 372 " this:logInfo(\"end_request_service:\" + ph + \":\" +service );" "SansSerif" 1 16 0 REF 87 
            CH.ifa.draw.standard.OffsetLocator 107 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2546 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 416 251 "this:logInfo(\"start_request_service:\" + ph + \":\" +service );" "SansSerif" 1 16 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 167 28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1994 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 493 278 "ph:getService(service)" "SansSerif" 1 16 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 85 55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2003 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 558 360 "service provider" "SansSerif" 1 16 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 19 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2548 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 198 369 "\nthis:logInfo(\"provider_service:\" + provider + \":\" +service );" "SansSerif" 1 16 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 155 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2188 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1953 1032 "rhm:netId(holonId)" "SansSerif" 1 16 0 REF 228 
            CH.ifa.draw.standard.OffsetLocator 108 13 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2189 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1953 1012 "rhm:publishServices(services)" "SansSerif" 1 16 0 REF 228 
            CH.ifa.draw.standard.OffsetLocator 158 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2191 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1904 1132 "rhm" "SansSerif" 1 16 0 REF 202 
            CH.ifa.draw.standard.OffsetLocator -5 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2161 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1796 1174 "guard x > 0" "SansSerif" 1 16 0 REF 201 
            CH.ifa.draw.standard.OffsetLocator -78 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2163 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1980 1148 "x-1" "SansSerif" 1 16 0 REF 211 
            CH.ifa.draw.standard.OffsetLocator 21 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2164 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1964 1121 "x" "SansSerif" 1 16 0 REF 207 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2162 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2007 1105 "1" "SansSerif" 1 16 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2170 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1797 1200 "rhm: new resourceHolon(holonId)" "SansSerif" 1 16 0 REF 201 
            CH.ifa.draw.standard.OffsetLocator 21 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2032 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1904 525 "rht:netId(holonId)" "SansSerif" 1 16 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 99 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1979 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1906 498 "rht:publishServices(services)" "SansSerif" 1 16 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 151 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2192 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1744 1104 "waiting to initialize" "SansSerif" 1 16 0 REF 200 
            CH.ifa.draw.standard.OffsetLocator -102 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2165 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 2021 1105 "add\nMachines" "SansSerif" 1 16 0 REF 206 
            CH.ifa.draw.standard.OffsetLocator 48 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1973 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1699 594 "waiting to initialize" "SansSerif" 1 16 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -104 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1985 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1870 555 "rht" "SansSerif" 1 16 0 REF 52 
            CH.ifa.draw.standard.OffsetLocator -1 5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1888 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1757 677 "guard x > 0" "SansSerif" 1 16 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -75 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1933 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1871 634 "rht" "SansSerif" 1 16 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 1 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1890 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1909 620 "x-1" "SansSerif" 1 16 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator -1 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1887 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1963 610 "add\ntransporters" "SansSerif" 1 16 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 52 10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1889 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1964 609 "1" "SansSerif" 1 16 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 1 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1884 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1758 699 "rht: new resourceHolon(holonId)" "SansSerif" 1 16 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 20 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1950 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1334 723 "action holonId = pt.nfriacowboy.presib.hermes.utils.PresibUtils.Companion.holonIdBuilder(\"rht\", x)" "SansSerif" 1 16 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator -112 49 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1962 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1326 1232 "action holonId = pt.nfriacowboy.presib.hermes.utils.PresibUtils.Companion.holonIdBuilder(\"rhm\", x)" "SansSerif" 1 16 0 REF 201 
            CH.ifa.draw.standard.OffsetLocator -158 56 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2474 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1141 572 "rht:endServiceExecution()" "SansSerif" 1 16 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator -16 61 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2543 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1141 555 "this:logInfo(\"end_service:\" + holonId + \":\" +ph );" "SansSerif" 1 16 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 84 44 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2143 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1137 532 "ph:currentTransportService(services)" "SansSerif" 1 16 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 33 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2511 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 1359 1110 "[holonId, rhm]" "SansSerif" 1 16 0 REF 483 
            CH.ifa.draw.standard.OffsetLocator 77 27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2345 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1141 1078 "rhm:endServiceExecution()" "SansSerif" 1 16 0 REF 299 
            CH.ifa.draw.standard.OffsetLocator 10 56 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 2544 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 1143 1063 "this:logInfo(\"end_service:\" + holonId + \":\" +ph );" "SansSerif" 1 16 0 REF 299 
            CH.ifa.draw.standard.OffsetLocator 108 41 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  