11 
    de.renew.gui.CPNDrawing 19 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 25 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 217 169 24 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 210 148 "recive" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 2 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 27 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 341 177 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 19 405 207 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 29 2 360 191 405 209 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 5  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 33 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 134 201 ":incomingMessage(info);\n" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -19 39 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 34 2 241 177 342 187 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector REF 5   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 35 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 266 147 "info.toString()" "SansSerif" 0 12 0 REF 14 
            CH.ifa.draw.standard.OffsetLocator 18 -28 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 37 410 311 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 38 2 417 223 420 312 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1039 "FillColor" "Color" 112 219 147 255 194 440 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1040 "FillColor" "Color" 112 219 147 255 299 437 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1041 "FillColor" "Color" 112 219 147 255 241 479 24 16 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1042 "FillColor" "Color" 112 219 147 255 242 418 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1046 2 212 456 242 479 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 28   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1047 2 264 479 302 453 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 28  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1048 2 301 444 266 430 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 29   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1049 2 242 431 213 447 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 29  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1043 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 199 445 "[]" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  382 345 598 600 