11 
    de.renew.gui.CPNDrawing 40 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1145 "FillColor" "Color" 112 219 147 255 138 146 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1146 2 148 166 148 255 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1150 "FillColor" "Color" 112 219 147 255 137 255 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1147 2 149 271 151 332 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1149 "FillColor" "Color" 112 219 147 255 141 331 20 20 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1148 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 143 149 "[]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1109 "FillColor" "Color" 112 219 147 255 856 254 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1110 "FillColor" "Color" 112 219 147 255 932 451 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1111 2 870 273 940 451 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 16   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1112 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 848 355 "\"motion detected\"" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1113 "FillColor" "Color" 112 219 147 255 943 108 24 16 NULL  REF 11 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1115 "FillColor" "Color" 112 219 147 255 1045 389 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1116 "FillColor" "Color" 112 219 147 255 1023 119 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1117 2 967 118 1024 128 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 24  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1118 2 956 452 1047 404 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 16  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1119 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 925 90 "motionOff" "SansSerif" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 5 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1120 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 914 478 "motionOn" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 4 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 6 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1151 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 139 292 "client" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator 6 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1152 "FillColor" "Color" 112 219 147 255 139 416 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1124 2 871 256 950 124 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1125 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 856 183 "\"motion stopped\"" "SansSerif" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1153 "FillColor" "Color" 112 219 147 255 332 251 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1154 "FillColor" "Color" 112 219 147 255 331 347 24 16 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FrameColor" "Color" 0 0 0 255 "FigureWithID" "Int" 1155 "FillColor" "Color" 112 219 147 255 519 344 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1156 2 355 354 520 354 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 53  
            CH.ifa.draw.figures.ChopEllipseConnector REF 54   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1157 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 169 193 "action communicator = new CommunicationClient();" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 182 -63 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1158 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 170 209 "action client.connect();" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 94 -47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1159 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 171 226 "action client.messageProcessor(communicator);" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 174 -30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1160 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 170 178 "action client = new pt.nfriacowboy.presib.hermes.MqttClient(\"netIdTeste\");" "SansSerif" 0 12 0 REF 6 
            CH.ifa.draw.standard.OffsetLocator 254 -78 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1161 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 410 339 "message" "SansSerif" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 1 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1162 2 342 271 342 347 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 52  
            CH.ifa.draw.standard.ChopBoxConnector REF 53   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1163 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 296 302 " communicator" "SansSerif" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1164 2 161 262 333 261 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector REF 52   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1165 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 203 254 "communicator" "SansSerif" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 1166 2 151 351 151 416 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1167 "TextAlignment" "Int" 1 "FillColor" "Color" 254 254 254 255 134 376 "client" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1168 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 81 435 ":subscribeTopic(topic)" "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator -1 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1169 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 82 454 "client.subscribe(topic); " "SansSerif" 0 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 5 37 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1170 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 320 371 "communicator:getMessage(message);" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 97 23 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FrameColor" "Color" 255 199 158 255 "FigureWithID" "Int" 1171 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 314 393 ":onMessage(message)" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 42 45 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  1281 100 1168 750 